### ISSUE TITLE
Modularizing Passportjs and integrating it with the rest of the modules/models.

### ISSUE THREAD

**Issue by interglobalmedia2** [NYCDA-HEROS/instagram-clone-app#27]
I have been stuck on this, and could use some big help. I will share what I have done, and James/Hossam, if you want to take a crack at it. I will explain and show an example of what I am trying to achieve. I will share links here as well. This has to be done pronto before we can then go to the pics/comments/tags step. Those also have to be modularized into models. But once the user is set up via passport, that part will be much easier. However, since this seems to be very hard to integrate and might take too much time, we can skip this step for this project.

**Comment by interglobalmedia2** [comment]
We are no longer using passport.js but express-sessions and bcrypt. James and I followed this tutorial I came across in a Google search here for getting it set up and then integratable with the the other models. Link here: https://www.codementor.io/mayowa.a/how-to-build-a-simple-session-based-authentication-system-with-nodejs-from-scratch-6vn67mcy3

**Comment by interglobalmedia2** [comment]
FYI: when I logged out and tried to log in, I came across the following error in Terminal Console:

```

POST /login - - ms - -
Executing (default): SELECT "id", "username", "email", "password", "createdAt", "updatedAt" FROM "users" AS "users" WHERE "users"."username" = 'maria';
Unhandled rejection TypeError: user.validPassword is not a function
    at /Users/postgres/postgres-development/express-authentication/models/user.js:140:30
    at tryCatcher (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/postgres/postgres-development/express-authentication/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

POST /login - - ms - -
```
Then I went back into the article to see if anyone had anything to say about this, and one person did! He said the following in a comment below:
```
Hi,
With sequelize v4 you need to remove in the user.js this code:
,
instanceMethods: {
validPassword: function(password) {
return bcrypt.compareSync(password, this.password);
}
}
and add :
User.prototype.validPassword = function (password) {
return bcrypt.compareSync(password, this.password);
};

I hope it helps!

PS: nice tuto !
```
Am implementing it now.

**Comment by interglobalmedia2** [comment]
BTW, the hack works!
